Repository wecode-bootcamp-korea/39-backend-westagram-2, pull requests merged in 2022-11, with the labels that each got.

#1 [김세호] Assignment 1: Express API - 초기 환경 세팅
  .gitignore
  Kimseho_assignment/.env.sample
  Kimseho_assignment/.gitignore
  Kimseho_assignment/app.js
  Kimseho_assignment/db/migrations/20221102035926_create_users_table.sql
  Kimseho_assignment/db/migrations/20221102041241_create_posts_table.sql
  Kimseho_assignment/db/migrations/20221102042704_create_likes_table.sql
  Kimseho_assignment/package-lock.json
  Kimseho_assignment/package.json
Labels: 멘토 리뷰 요청

#4 [김한솔] Assignment 1: Express API - 초기환경세팅
  hansol/.env.sample
  hansol/app.js
  hansol/package-lock.json
  hansol/package.json
Labels: 멘토 리뷰 요청

#5 [김세호] Assignment 2: 유저 회원가입 하기
  .gitignore
  Kimseho_assignment/app.js
Labels: 수정 요청

#10 [김수정]Assignment 1: Express API -초기환경세팅
  sujeong/.env.sample
  sujeong/.gitignore
  sujeong/app.js
  sujeong/package-lock.json
  sujeong/package.json
Labels: 수정 요청

#6 [송철진] Assignment 1: Express API - 초기환경세팅
  chuljin/.env.sample
  chuljin/.gitignore
  chuljin/app.js
  chuljin/db/migrations/20221103053015_create_users_table.sql
  chuljin/db/migrations/20221103053026_create_posts_table.sql
  chuljin/db/migrations/20221103053040_create_likes_table.sql
  chuljin/db/migrations/20221103053100_create_comments_table.sql
  chuljin/package-lock.json
  chuljin/package.json
Labels: 멘토 리뷰 요청

#2 [이동근] Assignment 1: Express API - 초기환경세팅
  dongken/.env.sample
  dongken/.gitignore
  dongken/app.js
  dongken/package-lock.json
  dongken/package.json
Labels: Assignment 1 - 리뷰 선반영 요청

#14 [39기 송철진] ADD : 유저 회원가입 하기
  chuljin/app.js
Labels: 멘토 리뷰 요청

#7 [이동근] Assignment 2: Express API -유저회원가입하기
  dongken/.gitignore
  dongken/db/migrations/20221102083732_create_users_table.sql
Labels: 수정 요청

#12 [김세호] Assignment 3~8 : 게시글 등록 ~좋아요 누르기
  Kimseho_assignment/.env.sample
  Kimseho_assignment/app.js
  Kimseho_assignment/db/migrations/20221102035926_create_users_table.sql
  Kimseho_assignment/package-lock.json
  Kimseho_assignment/package.json
Labels: 도움 요청

#9 [이동근] Assignment 3: Express API -게시글 등록하기
  dongken/.gitignore
  dongken/app.js
  dongken/db/migrations/20221103014057_create.users.table.sql
  dongken/db/migrations/20221103014118_create.posts.table.sql
  dongken/db/migrations/20221107042405_create_likes_table.sql
Labels: Assignment 1 - 리뷰 선반영 요청

#16 [39기 송철진] ADD : Assignment#3 게시글 등록하기
  chuljin/app.js
Labels: 멘토 리뷰 요청

#15 [김수정]Assignment2:ExpressAPI-유저회원가입
  sujeong/app.js
Labels: 멘토 리뷰 요청

#8 [김한솔] Assignment 2: Express API -유저회원가입하기
  hansol/.gitignore
  hansol/app.js
  hansol/db/migrations/20221102080531_create_users.sql
  hansol/db/migrations/20221102080543_create_posts.sql
  hansol/db/migrations/20221102122928_create_comments_table.sql
  hansol/db/migrations/20221102122936_create_likes_table.sql
  hansol/db/migrations/20221103072108_create_posts_update.sql
Labels: 수정 요청

#17 [김한솔] Assignment 3-8 : 게시글 등록 - 좋아요 기능
  hansol/.env.sample
  hansol/.gitignore
  hansol/app.js
  hansol/db/migrations/20221102080531_create_users.sql
  hansol/db/migrations/20221102122928_create_comments_table.sql
  hansol/db/migrations/20221102122936_create_likes_table.sql
  hansol/package-lock.json
  hansol/package.json
Labels: 멘토 리뷰 요청

#19 [39기 송철진] Modify : 불필요한 콘솔로그, 변수 삭제
  chuljin/app.js
Labels: 멘토 리뷰 요청

#22 [김세호] Assignment 1~2 : Bcrypt Verification 및 JWT 발급하기
  Kimseho_assignment/app.js
  Kimseho_assignment/package-lock.json
  Kimseho_assignment/package.json
Labels: 멘토 리뷰 요청

#23 [김한솔] Assignment 1~3 : 암호화 & JWT 발급 & 게시글 등록하기
  hansol/app.js
  hansol/package-lock.json
  hansol/package.json
  hansol/withAuth.js
Labels: 멘토 리뷰 요청

#21 [김수정] Assignment 3~8: 게시글 등록하기~좋아요 누르기
  sujeong/.gitignore
  sujeong/app.js
  sujeong/db/migrations/20221107121254_create_users_table.sql
  sujeong/db/migrations/20221107121305_create_posts_table.sql
  sujeong/db/migrations/20221108082013_create_likes_table.sql
  sujeong/package-lock.json
  sujeong/package.json
Labels: 멘토 리뷰 요청
